name: liss-data
channels:
  - opensourceeconomics
  - conda-forge
  - defaults
  - pytask
dependencies:
  - pytask
  - pytask-parallel
  - conda-build
  - utilities
  - jupyterlab
  - mock
  - nose
  - pandas>=1.0.2
  - pip
  - python=3.7
  - pyyaml
  - scikit-learn
  - seaborn>=0.9
  - sphinx
  - sphinxcontrib-bibtex
  - xlrd
  - html5lib
  - lxml
  - openpyxl
  - nodejs
  - nb_black

  - pip:
    - pre-commit==1.18.3

    - savReaderWriter
    - pyreadstat
